In [4]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [6]:
b = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
c = np.ones((3, 4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
b.sum() #soma
b.mean() #média 
b.std() #desvio padrão

2.581988897471611